spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://localhost:3307/blog?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: mysqlmima0210
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true


server:
  port: 8080

# SpringDoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# JWT配置
jwt:
  secret: woshilllllllll  # 生产环境请使用更复杂的密钥
  expiration: 86400000         # 24小时，单位：毫秒

# 应用配置
app:
  upload:
    dir: uploads              # 上传目录（开发环境：相对路径，Docker环境：可挂载卷）
    base-url: http://localhost:8080  # 开发环境的基础URL

---
# Docker环境配置
spring:
  config:
    activate:
      on-profile: docker

app:
  upload:
    dir: /app/uploads        # Docker环境中的上传目录
    base-url: ${SERVER_BASE_URL:http://localhost:8080}  # 可通过环境变量设置